// // import 'package:latlong2/latlong.dart';

// class Casino {
//   Casino(
//     this.name,
//     this.location,
//     this.country,
//     this.website,
//   );

//   final String name;
//   final LatLng location;
//   final String country;
//   final String website;
// }

// final List<LatLng> centers = [
//   const LatLng(37.7749, -122.4194), // USA
//   const LatLng(45.4215, -75.6972), // Canada
//   const LatLng(51.5074, -0.1278), // UK
//   const LatLng(46.8182, 8.2275), // Switzerland
//   const LatLng(-33.8688, 151.2093), // Australia
//   const LatLng(22.3193, 114.1694), // China
//   const LatLng(51.1657, 10.4515), // Germany
//   const LatLng(12.8797, 121.7740), // Philippines
// ];

// final Map<String, List<Casino>> countryCasinos = {
//   'USA': [
//     // Alabama
//     Casino('Victoryland', const LatLng(32.3911, -85.8999), 'USA',
//         'https://www.victoryland.com'),
//     Casino('Wind Creek Casino & Hotel Atmore', const LatLng(31.0253, -87.4848),
//         'USA', 'https://www.windcreekatmore.com'),
//     Casino(
//         'Wind Creek Casino & Hotel Montgomery',
//         const LatLng(32.3792, -86.3077),
//         'USA',
//         'https://www.windcreekmontgomery.com'),
//     Casino(
//         'Wind Creek Casino & Hotel Wetumpka',
//         const LatLng(32.5436, -86.2118),
//         'USA',
//         'https://www.windcreekwetumpka.com'),
//     // Arizona
//     Casino('Apache Gold Casino Resort', const LatLng(33.3553, -110.4523), 'USA',
//         'https://www.apachegoldcasino.com'),
//     Casino('Apache Sky Casino', const LatLng(32.9086, -110.7379), 'USA',
//         'https://www.apacheskycasino.com'),
//     Casino('BlueWater Resort and Casino', const LatLng(34.1645, -114.2834),
//         'USA', 'https://www.bluewaterfun.com'),
//     Casino('Bucky\'s Casino', const LatLng(34.5414, -112.4685), 'USA',
//         'https://www.buckyscasino.com'),
//     Casino('Casino Arizona', const LatLng(33.5319, -111.9266), 'USA',
//         'https://www.casinoarizona.com'),
//     Casino('Casino del Sol', const LatLng(32.1297, -111.0682), 'USA',
//         'https://www.casinodelsol.com'),
//     Casino('Casino of the Sun', const LatLng(32.1073, -111.0974), 'USA',
//         'https://www.casinodelsol.com'),
//     Casino('Cliff Castle Casino', const LatLng(34.5614, -111.8577), 'USA',
//         'https://www.cliffcastlecasinohotel.com'),
//     Casino('Cocopah Resort Casino', const LatLng(32.5932, -114.7071), 'USA',
//         'https://www.cocopahresort.com'),
//     Casino('Desert Diamond Casino', const LatLng(31.7446, -111.6008), 'USA',
//         'https://www.ddcaz.com'),
//     Casino('Desert Diamond Casino, Sahuarita', const LatLng(31.9574, -110.9572),
//         'USA', 'https://www.ddcaz.com'),
//     Casino('Desert Diamond Casino–West Valley',
//         const LatLng(33.5271, -112.2583), 'USA', 'https://www.ddcaz.com'),
//     Casino('Desert Diamond Hotel & Casino', const LatLng(32.1059, -111.0363),
//         'USA', 'https://www.ddcaz.com'),
//     Casino('We-Ko-PA Casino & Resort', const LatLng(33.6053, -111.7178), 'USA',
//         'https://www.wekopacasinoresort.com'),
//     Casino('Harrah\'s Ak-Chin Casino', const LatLng(33.0282, -112.0468), 'USA',
//         'https://www.caesars.com/harrahs-ak-chin'),
//     Casino('Hon-Dah Resort Casino', const LatLng(34.1069, -109.9601), 'USA',
//         'https://www.hon-dah.com'),
//     Casino('Lone Butte Casino', const LatLng(33.2707, -111.9182), 'USA',
//         'https://www.wingilariver.com'),
//     Casino('Mazatzal Casino', const LatLng(34.2309, -111.3185), 'USA',
//         'https://www.mazatzalcasino.com'),
//     Casino('Paradise Casino', const LatLng(32.6929, -114.6156), 'USA',
//         'https://www.paradisecasinoaz.com'),
//     Casino('Santan Mountain Hotel & Casino', const LatLng(33.2734, -111.7687),
//         'USA', 'https://www.wingilariver.com'),
//     Casino('Spirit Mountain Casino', const LatLng(34.8983, -114.6116), 'USA',
//         'https://www.spiritmountain.com'),
//     Casino('Talking Stick Resort', const LatLng(33.5446, -111.8992), 'USA',
//         'https://www.talkingstickresort.com'),
//     Casino('Twin Arrows Casino Resort', const LatLng(35.2024, -111.2386), 'USA',
//         'https://www.twinarrows.com'),
//     Casino('Vee Quiva Hotel & Casino', const LatLng(33.2892, -112.1614), 'USA',
//         'https://www.wingilariver.com'),
//     Casino('Wild Horse Pass Hotel & Casino', const LatLng(33.2757, -111.9736),
//         'USA', 'https://www.wingilariver.com'),
//     Casino('Yavapai Casino', const LatLng(34.5425, -112.4684), 'USA',
//         'https://www.yavapaicasino.com'),
//     // Arkansas
//     Casino('Oaklawn Racing Casino Resort', const LatLng(34.4964, -93.0538),
//         'USA', 'https://www.oaklawn.com'),
//     Casino('Saracen Casino Resort', const LatLng(34.2248, -92.0032), 'USA',
//         'https://www.saracenresort.com'),
//     Casino('Southland Casino', const LatLng(35.1494, -90.1845), 'USA',
//         'https://www.southlandcasino.com'),
//     // California
//     Casino(
//         'Aqua Caliente Casino Palm Springs',
//         const LatLng(33.8303, -116.5453),
//         'USA',
//         'https://www.hotwatercasino.com'),
//     Casino('Agua Caliente Casino', const LatLng(33.7806, -116.4088), 'USA',
//         'https://www.hotwatercasino.com'),
//     Casino('Augustine Casino', const LatLng(33.6138, -116.2162), 'USA',
//         'https://www.augustinecasino.com'),
//     Casino('Barona Valley Ranch Resort and Casino',
//         const LatLng(32.9210, -116.8675), 'USA', 'https://www.barona.com'),
//     Casino('Bear River Casino', const LatLng(40.6551, -124.1970), 'USA',
//         'https://www.bearrivercasino.com'),
//     Casino('Black Bart Casino', const LatLng(39.4091, -123.3538), 'USA',
//         'https://www.blackbartcasino.com'),
//     Casino('Black Oak Casino', const LatLng(37.9820, -120.2377), 'USA',
//         'https://www.blackoakcasino.com'),
//     Casino('Blue Lake Casino', const LatLng(40.8800, -123.9804), 'USA',
//         'https://www.bluelakecasino.com'),
//     Casino('Cache Creek Casino Resort', const LatLng(38.7703, -122.1332), 'USA',
//         'https://www.cachecreek.com'),
//     Casino('Cahuilla Creek Casino', const LatLng(33.5544, -116.7364), 'USA',
//         'https://www.cahuillacasino.com'),
//     Casino('Casino Pauma', const LatLng(33.3150, -116.9972), 'USA',
//         'https://www.casinopauma.com'),
//     Casino('Cher-Ae Heights Bingo and Casino', const LatLng(41.0583, -124.1458),
//         'USA', 'https://www.cheraeheightscasino.com'),
//     Casino('Chicken Ranch Bingo and Casino', const LatLng(37.9580, -120.4252),
//         'USA', 'https://www.chickenranchcasino.com'),
//     Casino('Chukchansi Gold Resort & Casino', const LatLng(37.2158, -119.7271),
//         'USA', 'https://www.chukchansigold.com'),
//     Casino('Chumash Casino Resort', const LatLng(34.6100, -120.0888), 'USA',
//         'https://www.chumashcasino.com'),
//     Casino('Colusa Casino Resort', const LatLng(39.1961, -122.0095), 'USA',
//         'https://www.colusacasino.com'),
//     Casino('Desert Rose Casino', const LatLng(41.4828, -120.5422), 'USA',
//         'https://www.desertrosecasino.com'),
//     Casino('Diamond Mountain Casino', const LatLng(40.4164, -120.6575), 'USA',
//         'https://www.dmc.com'),
//     Casino('Eagle Mountain Casino', const LatLng(36.0650, -118.8764), 'USA',
//         'https://www.eaglemtncasino.com'),
//     Casino('Elk Valley Casino', const LatLng(41.7681, -124.1930), 'USA',
//         'https://www.elkvalleycasino.com'),
//     Casino(
//         'Fantasy Springs Resort and Casino',
//         const LatLng(33.7248, -116.1859),
//         'USA',
//         'https://www.fantasyspringsresort.com'),
//     Casino('Feather Falls Casino', const LatLng(39.4862, -121.5231), 'USA',
//         'https://www.featherfallscasino.com'),
//     Casino('Gold Country Casino and Hotel', const LatLng(39.5163, -121.5683),
//         'USA', 'https://www.goldcountrycasino.com'),
//     Casino('Golden Acorn Casino', const LatLng(32.6714, -116.3290), 'USA',
//         'https://www.goldenacorncasino.com'),
//     Casino('Graton Resort & Casino', const LatLng(38.3653, -122.7190), 'USA',
//         'https://www.gratonresortcasino.com'),
//     Casino('Hard Rock Hotel & Casino', const LatLng(39.0443, -121.5621), 'USA',
//         'https://www.hardrockhotelsacramento.com'),
//     Casino('Harrah\'s Northern California', const LatLng(38.3525, -120.9332),
//         'USA', 'https://www.caesars.com/harrahs-northern-california'),
//     Casino(
//         'Harrah\'s Resort Southern California',
//         const LatLng(33.2961, -116.9583),
//         'USA',
//         'https://www.caesars.com/harrahs-socal'),
//     Casino('Havasu Landing Resort and Casino', const LatLng(34.4742, -114.3576),
//         'USA', 'https://www.havasulanding.com'),
//     Casino('Jackson Rancheria Casino', const LatLng(38.3613, -120.7743), 'USA',
//         'https://www.jacksoncasino.com'),
//     Casino('Jamul Casino', const LatLng(32.7137, -116.8765), 'USA',
//         'https://www.jamulcasinosd.com'),
//     Casino('Konocti Vista Casino and Bingo', const LatLng(39.0106, -122.8772),
//         'USA', 'https://www.konocti-vista-casino.com'),
//     Casino('La Jolla Slot Arcade', const LatLng(33.2655, -116.8847), 'USA',
//         'https://www.lajollaslotarcade.com'),
//     Casino('La Posta Casino', const LatLng(32.6747, -116.3009), 'USA',
//         'https://www.lapostacasino.com'),
//     Casino('Lucky 7 Casino', const LatLng(41.9400, -124.1950), 'USA',
//         'https://www.lucky7casino.com'),
//     Casino('Lucky Bear Casino', const LatLng(41.0473, -123.6729), 'USA',
//         'https://www.luckybearcasino.com'),
//     Casino('Mono Wind Casino', const LatLng(37.0744, -119.4797), 'USA',
//         'https://www.monowind.com'),
//     Casino('Morongo Casino, Resort & Spa', const LatLng(33.9192, -116.7920),
//         'USA', 'https://www.morongocasinoresort.com'),
//     Casino('Paiute Palace Casino', const LatLng(37.3634, -118.3943), 'USA',
//         'https://www.paiutepalace.com'),
//     Casino('Pala Casino Resort and Spa', const LatLng(33.3658, -117.0753),
//         'USA', 'https://www.palacasino.com'),
//     Casino('Pechanga Resort and Casino', const LatLng(33.4507, -117.1077),
//         'USA', 'https://www.pechanga.com'),
//     Casino('Pit River Casino', const LatLng(41.0188, -121.4986), 'USA',
//         'https://www.pitrivercasino.com'),
//     Casino('Quechan Resort Casino', const LatLng(32.7346, -114.6244), 'USA',
//         'https://www.playqrc.com'),
//     Casino('Rain Rock Casino', const LatLng(41.7271, -122.6346), 'USA',
//         'https://www.rainrockcasino.com'),
//     Casino('Red Earth Casino', const LatLng(33.2992, -115.7173), 'USA',
//         'https://www.redearthcasino.com'),
//     Casino('Red Fox Casino', const LatLng(39.6928, -123.4872), 'USA',
//         'https://www.redfoxcasino.com'),
//     Casino('Redhawk Casino', const LatLng(38.6931, -120.9876), 'USA',
//         'https://www.redhawkcasino.com'),
//     Casino('River Rock Casino', const LatLng(38.7225, -122.9178), 'USA',
//         'https://www.riverrockcasino.com'),
//     Casino('Robinson Rancheria Resort and Casino',
//         const LatLng(39.1264, -122.9111), 'USA', 'https://www.rrrc.com'),
//     Casino('Rolling Hills Casino', const LatLng(39.9348, -122.1339), 'USA',
//         'https://www.rollinghillscasino.com'),
//     Casino('San Pablo Lytton Casino', const LatLng(37.9627, -122.3426), 'USA',
//         'https://www.sanpablolytton.com'),
//     Casino('Santa Ysabel Resort and Casino', const LatLng(33.1227, -116.6739),
//         'USA', 'https://www.santaysabelcasino.com'),
//     Casino('Shodokai Casino', const LatLng(39.3254, -123.2109), 'USA',
//         'https://www.shodokaicasino.com'),
//     Casino('Sho-Ka-Wah Casino', const LatLng(38.7986, -123.0927), 'USA',
//         'https://www.shokawah.com'),
//     Casino('Sky River Casino', const LatLng(38.4098, -121.3542), 'USA',
//         'https://www.skyriver.com'),
//     Casino('Soboba Casino Resort', const LatLng(33.7831, -116.9150), 'USA',
//         'https://www.soboba.com'),
//     Casino('Spotlight 29 Casino', const LatLng(33.6780, -116.1872), 'USA',
//         'https://www.spotlight29.com'),
//     Casino('Sycuan Resort and Casino', const LatLng(32.7087, -116.8883), 'USA',
//         'https://www.sycuan.com'),
//     Casino('Table Mountain Casino', const LatLng(36.9828, -119.7083), 'USA',
//         'https://www.tmcasino.com'),
//     Casino('Tachi Palace Hotel and Casino', const LatLng(36.2989, -119.7639),
//         'USA', 'https://www.tachipalace.com'),
//     Casino('Thunder Valley Casino Resort', const LatLng(38.7994, -121.2836),
//         'USA', 'https://www.thundervalleyresort.com'),
//     Casino('Tortoise Rock Casino', const LatLng(34.1356, -116.0542), 'USA',
//         'https://www.tortoiserockcasino.com'),
//     Casino('Twin Pine Casino', const LatLng(38.8065, -122.5561), 'USA',
//         'https://www.twinpine.com'),
//     Casino('Valley View Casino', const LatLng(33.2409, -116.9414), 'USA',
//         'https://www.valleyviewcasino.com'),
//     Casino('Viejas Casino', const LatLng(32.8617, -116.6828), 'USA',
//         'https://www.viejas.com'),
//     Casino('Win-River Casino', const LatLng(40.5315, -122.3473), 'USA',
//         'https://www.winriver.com'),
//     Casino('Yaamava\' Resort & Casino', const LatLng(34.1431, -117.2876), 'USA',
//         'https://www.yaamava.com'),
//     // Colorado
//     Casino('Ameristar Black Hawk', const LatLng(39.8012, -105.4912), 'USA',
//         'https://www.ameristarblackhawk.com'),
//     Casino('Bally\'s Black Hawk East', const LatLng(39.8034, -105.4914), 'USA',
//         'https://www.ballys.com'),
//     Casino('Bally\'s Black Hawk North', const LatLng(39.8024, -105.4921), 'USA',
//         'https://www.ballys.com'),
//     Casino('Bally\'s Black Hawk West', const LatLng(39.8012, -105.4912), 'USA',
//         'https://www.ballys.com'),
//     Casino('Brass Ass Casino', const LatLng(38.7463, -105.1885), 'USA',
//         'https://www.thebrassass.com'),
//     Casino('Bronco Billy\'s Casino', const LatLng(38.7477, -105.1870), 'USA',
//         'https://www.broncobillys.com'),
//     Casino('Bull Durham Saloon and Casino', const LatLng(39.8002, -105.4912),
//         'USA', 'https://www.bulldurhamcasino.com'),
//     Casino(
//         'Century Casino & Hotel Central City',
//         const LatLng(39.8000, -105.5122),
//         'USA',
//         'https://www.centurycasinos.com/central-city'),
//     Casino('Century Casino Cripple Creek', const LatLng(38.7466, -105.1849),
//         'USA', 'https://www.centurycasinos.com/cripple-creek'),
//     Casino('Colorado Grande Casino', const LatLng(38.7471, -105.1856), 'USA',
//         'https://www.coloradogrande.com'),
//     Casino('Double Eagle Hotel & Casino', const LatLng(38.7484, -105.1877),
//         'USA', 'https://www.doubleeaglehotel.com'),
//     Casino('Dostal Alley Casino', const LatLng(39.8014, -105.5142), 'USA',
//         'https://www.dostalalley.com'),
//     Casino('Famous Bonanza Casino', const LatLng(38.7482, -105.1856), 'USA',
//         'https://www.famousbonanzacasino.com'),
//     Casino('Fortune Valley Hotel & Casino', const LatLng(39.8012, -105.5136),
//         'USA', 'https://www.fortunevalleyhotel.com'),
//     Casino('Gilpin Hotel Casino', const LatLng(39.8002, -105.4921), 'USA',
//         'https://www.gilpincasino.com'),
//     Casino('Gold Creek Casino', const LatLng(38.7472, -105.1884), 'USA',
//         'https://www.goldcreekcasino.com'),
//     Casino('Golden Gates Casino', const LatLng(39.8002, -105.4926), 'USA',
//         'https://www.goldengatescasino.com'),
//     Casino('Golden Gulch Casino', const LatLng(39.8002, -105.4926), 'USA',
//         'https://www.goldengulchcasino.com'),
//     Casino('Grand Z Casino Hotel', const LatLng(39.7984, -105.5148), 'USA',
//         'https://www.grandzcasinohotel.com'),
//     Casino('Johnny Nolon\'s Casino', const LatLng(38.7484, -105.1868), 'USA',
//         'https://www.johnnynolons.com'),
//     Casino('Lady Luck Casino Black Hawk', const LatLng(39.8012, -105.4914),
//         'USA', 'https://www.ladyluckblackhawk.com'),
//     Casino('Lodge Casino at Black Hawk', const LatLng(39.8012, -105.4912),
//         'USA', 'https://www.thelodgecasino.com'),
//     Casino('Monarch Casino Black Hawk', const LatLng(39.8006, -105.4912), 'USA',
//         'https://www.monarchblackhawk.com'),
//     Casino('Red Dolly Casino', const LatLng(39.8012, -105.4912), 'USA',
//         'https://www.reddollycasino.com'),
//     Casino('Saratoga Casino Black Hawk', const LatLng(39.8012, -105.4912),
//         'USA', 'https://www.saratogacasino.com'),
//     Casino('Saratoga Casino', const LatLng(39.8012, -105.4912), 'USA',
//         'https://www.saratogacasino.com'),
//     Casino('Sky Ute Casino Resort', const LatLng(37.0881, -107.6348), 'USA',
//         'https://www.skyutecasino.com'),
//     Casino('Sundance Casino', const LatLng(38.7474, -105.1857), 'USA',
//         'https://www.sundancecasino.com'),
//     Casino('Ute Mountain Casino Hotel', const LatLng(37.2892, -108.7436), 'USA',
//         'https://www.utemountaincasino.com'),
//     Casino('Wildwood Casino', const LatLng(38.7469, -105.1883), 'USA',
//         'https://www.wildwoodcasino.net'),
//     // Connecticut
//     Casino('Foxwoods Resort Casino', const LatLng(41.4731, -71.9619), 'USA',
//         'https://www.foxwoods.com'),
//     Casino('Mohegan Sun', const LatLng(41.4911, -72.0918), 'USA',
//         'https://www.mohegansun.com'),
//     // Delaware
//     Casino('Bally\'s Dover', const LatLng(39.1875, -75.5363), 'USA',
//         'https://www.ballysdover.com'),
//     Casino('Delaware Park Casino', const LatLng(39.7081, -75.6688), 'USA',
//         'https://www.delawarepark.com'),
//     Casino('Harrington Raceway & Casino', const LatLng(38.9181, -75.5805),
//         'USA', 'https://www.harringtonraceway.com'),
//     // Florida
//     Casino('Big Cypress Casino', const LatLng(26.3486, -81.1225), 'USA',
//         'https://www.bigcypresscasino.com'),
//     Casino('Coconut Creek Casino', const LatLng(26.3053, -80.1828), 'USA',
//         'https://www.casinococo.com'),
//     Casino('Gulfstream Park Casino', const LatLng(25.9808, -80.1373), 'USA',
//         'https://www.gulfstreampark.com'),
//     Casino('Isle Casino Pompano Park', const LatLng(26.2158, -80.1521), 'USA',
//         'https://www.islepompanopark.com'),
//     Casino('Miccosukee Resort & Gaming', const LatLng(25.7596, -80.5430), 'USA',
//         'https://www.miccosukee.com'),
//     Casino('Seminole Casino Brighton', const LatLng(27.1028, -81.0521), 'USA',
//         'https://www.seminolebrightoncasino.com'),
//     Casino('Seminole Casino Immokalee', const LatLng(26.4182, -81.4178), 'USA',
//         'https://www.seminoleimmokaleecasino.com'),
//     Casino(
//         'Seminole Casino Hotel Coconut Creek',
//         const LatLng(26.3053, -80.1828),
//         'USA',
//         'https://www.seminolecoconutcreekcasino.com'),
//     Casino('Seminole Hard Rock Hotel & Casino', const LatLng(26.0512, -80.2092),
//         'USA', 'https://www.seminolehardrockhollywood.com'),
//     Casino(
//         'Seminole Hard Rock Hotel & Casino Tampa',
//         const LatLng(27.9784, -82.3466),
//         'USA',
//         'https://www.seminolehardrocktampa.com'),
//     Casino('Victory Casino Cruises', const LatLng(28.3922, -80.6077), 'USA',
//         'https://www.victorycasinocruises.com'),
//   ],
//   'Canada': [
//     // Alberta
//     Casino('Century Casino Edmonton', const LatLng(53.5705, -113.4286),
//         'Canada', 'https://www.cnty.com/edmonton/'),
//     Casino('Grey Eagle Casino', const LatLng(51.0124, -114.1633), 'Canada',
//         'https://www.greyeagleresortandcasino.ca'),
//     Casino('River Cree Resort and Casino', const LatLng(53.4900, -113.6738),
//         'Canada', 'https://www.rivercreeresort.com'),
//     Casino('Pure Casino Yellowhead', const LatLng(53.5707, -113.5996), 'Canada',
//         'https://www.purecanada.com/yellowhead'),

//     // British Columbia
//     Casino('Parq Vancouver', const LatLng(49.2767, -123.1153), 'Canada',
//         'https://www.parqvancouver.com'),
//     Casino('River Rock Casino Resort', const LatLng(49.1941, -123.1317),
//         'Canada', 'https://www.riverrock.com'),
//     Casino('Hard Rock Casino Vancouver', const LatLng(49.2330, -122.7963),
//         'Canada', 'https://hardrockcasinovancouver.com'),
//     Casino('Cascades Casino', const LatLng(49.1046, -122.6626), 'Canada',
//         'https://www.cascadescasino.ca'),

//     // Manitoba
//     Casino('Club Regent Casino', const LatLng(49.8901, -97.0559), 'Canada',
//         'https://www.casinosofwinnipeg.com/club-regent-casino'),
//     Casino(
//         'McPhillips Station Casino',
//         const LatLng(49.9222, -97.1812),
//         'Canada',
//         'https://www.casinosofwinnipeg.com/mcphillips-station-casino'),

//     // New Brunswick
//     Casino('Casino New Brunswick', const LatLng(46.1236, -64.8190), 'Canada',
//         'https://casinonb.ca'),

//     // Nova Scotia
//     Casino('Casino Nova Scotia Halifax', const LatLng(44.6493, -63.5739),
//         'Canada', 'https://casinonovascotia.com/halifax'),
//     Casino('Casino Nova Scotia Sydney', const LatLng(46.1380, -60.1968),
//         'Canada', 'https://casinonovascotia.com/sydney'),

//     // Ontario
//     Casino('Casino Rama Resort', const LatLng(44.6492, -79.3545), 'Canada',
//         'https://www.casinorama.com'),
//     Casino('Caesars Windsor', const LatLng(42.3208, -83.0394), 'Canada',
//         'https://www.caesars.com/caesars-windsor'),
//     Casino('Fallsview Casino Resort', const LatLng(43.0816, -79.0747), 'Canada',
//         'https://www.fallsviewcasinoresort.com'),
//     Casino('Casino Niagara', const LatLng(43.0902, -79.0747), 'Canada',
//         'https://www.casinoniagara.com'),
//     Casino('Elements Casino Brantford', const LatLng(43.1657, -80.2513),
//         'Canada', 'https://www.elementscasinobrantford.com'),
//     Casino('Gateway Casinos London', const LatLng(42.9420, -81.2330), 'Canada',
//         'https://www.gatewaycasinos.com/casinos/london'),

//     // Quebec
//     Casino('Casino de Montréal', const LatLng(45.5071, -73.5221), 'Canada',
//         'https://casinos.lotoquebec.com/en/montreal/home'),
//     Casino('Casino du Lac-Leamy', const LatLng(45.4370, -75.7353), 'Canada',
//         'https://casinos.lotoquebec.com/en/lacleamy/home'),
//     Casino('Casino de Charlevoix', const LatLng(47.6288, -70.1447), 'Canada',
//         'https://casinos.lotoquebec.com/en/charlevoix/home'),
//     Casino('Casino de Mont-Tremblant', const LatLng(46.2097, -74.5873),
//         'Canada', 'https://casinos.lotoquebec.com/en/mont-tremblant/home'),

//     // Saskatchewan
//     Casino('Casino Regina', const LatLng(50.4478, -104.6103), 'Canada',
//         'https://casinoregina.com'),
//     Casino('Gold Eagle Casino', const LatLng(52.7704, -108.3094), 'Canada',
//         'https://goldeaglecasino.ca'),
//     Casino('Northern Lights Casino', const LatLng(53.2140, -105.7507), 'Canada',
//         'https://northernlightscasino.ca'),

//     // Yukon
//     Casino(
//         'Diamond Tooth Gerties Gambling Hall',
//         const LatLng(64.0590, -139.4320),
//         'Canada',
//         'https://dawsoncity.ca/diamond-tooth-gerties')
//   ],
//   'United Kingdom': [
//     // England
//     Casino('Hippodrome Casino', const LatLng(51.5117, -0.1300),
//         'United Kingdom', 'https://www.hippodromecasino.com'),
//     Casino('Aspers Casino', const LatLng(51.5435, -0.0064), 'United Kingdom',
//         'https://www.aspersstratford.co.uk'),
//     Casino('Empire Casino', const LatLng(51.5102, -0.1312), 'United Kingdom',
//         'https://www.thecasinolsq.com'),
//     // Scotland
//     Casino('Grosvenor Casino, Glasgow', const LatLng(55.8606, -4.2575),
//         'United Kingdom', 'https://www.grosvenorcasinos.com'),
//     Casino('Aleas Casino, Glasgow', const LatLng(55.8623, -4.2546),
//         'United Kingdom', 'https://www.gentingcasino.com'),
//     // Wales
//     Casino('Grosvenor Casino, Cardiff', const LatLng(51.4712, -3.1791),
//         'United Kingdom', 'https://www.grosvenorcasinos.com'),
//     Casino('Les Croupiers Casino, Cardiff', const LatLng(51.4761, -3.1923),
//         'United Kingdom', 'https://www.lescroupiers.co.uk'),
//   ],
//   'Switzerland': [
//     // Zurich
//     Casino('Swiss Casinos Zurich', const LatLng(47.3769, 8.5417), 'Switzerland',
//         'https://www.swisscasinos.ch'),
//     Casino('Casino Zurichsee', const LatLng(47.2263, 8.8292), 'Switzerland',
//         'https://www.casinozuerichsee.ch'),
//     // Geneva
//     Casino('Casino du Lac Geneva', const LatLng(46.2311, 6.1149), 'Switzerland',
//         'https://www.casino-geneve.ch'),
//     // Basel
//     Casino('Grand Casino Basel', const LatLng(47.5743, 7.6113), 'Switzerland',
//         'https://www.grandcasinobasel.com'),
//     // Lucerne
//     Casino('Grand Casino Lucerne', const LatLng(47.0549, 8.3113), 'Switzerland',
//         'https://www.grandcasinoluzern.ch'),
//     // St. Gallen
//     Casino('Swiss Casinos St. Gallen', const LatLng(47.4239, 9.3748),
//         'Switzerland', 'https://www.swisscasinos.ch'),
//   ],
//   'Australia': [
//     // New South Wales
//     Casino('The Star, Sydney', const LatLng(33.8688, 151.2093), 'Australia',
//         'https://www.star.com.au/sydney'),
//     // Victoria
//     Casino('Crown Casino, Melbourne', const LatLng(37.8216, 144.9581),
//         'Australia', 'https://www.crownmelbourne.com.au'),
//     // Queensland
//     Casino('Treasury Casino, Brisbane', const LatLng(27.4710, 153.0234),
//         'Australia', 'https://www.treasurybrisbane.com.au'),
//     Casino('The Star Gold Coast', const LatLng(28.0296, 153.4319), 'Australia',
//         'https://www.star.com.au/goldcoast'),
//     // Western Australia
//     Casino('Crown Casino, Perth', const LatLng(31.9598, 115.8960), 'Australia',
//         'https://www.crownperth.com.au'),
//     // South Australia
//     Casino('SkyCity Adelaide', const LatLng(34.9228, 138.5999), 'Australia',
//         'https://www.skycityadelaide.com.au'),
//     // Tasmania
//     Casino('Wrest Point Casino, Hobart', const LatLng(42.8912, 147.3272),
//         'Australia', 'https://www.wrestpoint.com.au'),
//   ],
//   'China': [
//     // Macau
//     Casino('The Venetian Macao', const LatLng(22.1486, 113.5614), 'China',
//         'https://www.venetianmacao.com'),
//     Casino('City of Dreams', const LatLng(22.1441, 113.5634), 'China',
//         'https://www.cityofdreamsmacau.com'),
//     Casino('Wynn Macau', const LatLng(22.1841, 113.5567), 'China',
//         'https://www.wynnmacau.com'),
//     Casino('MGM Macau', const LatLng(22.1821, 113.5586), 'China',
//         'https://www.mgm.mo'),
//     Casino('Galaxy Macau', const LatLng(22.1497, 113.5529), 'China',
//         'https://www.galaxymacau.com'),
//     Casino('Sands Macao', const LatLng(22.1967, 113.5522), 'China',
//         'https://www.sandsmacao.com'),
//     Casino('Studio City Macau', const LatLng(22.1386, 113.5632), 'China',
//         'https://www.studiocity-macau.com'),
//     Casino('Grand Lisboa', const LatLng(22.1897, 113.5417), 'China',
//         'https://www.grandlisboahotels.com'),
//     Casino('Lisboa Casino', const LatLng(22.1857, 113.5419), 'China',
//         'https://www.hotelisboa.com'),
//     Casino('Altira Macau', const LatLng(22.1593, 113.5585), 'China',
//         'https://www.altiramacau.com'),
//     Casino('MGM Cotai', const LatLng(22.1445, 113.5694), 'China',
//         'https://www.mgm.mo/en/cotai'),
//     // Other regions
//     Casino('Shangri-La Sanya Resort and Spa', const LatLng(18.2284, 109.5102),
//         'China', 'https://www.shangri-la.com/sanya/shangrila'),
//   ],
//   'Germany': [
//     // Baden-Württemberg
//     Casino('Casino Baden-Baden', const LatLng(48.7606, 8.2398), 'Germany',
//         'https://www.casino-baden-baden.de'),
//     // Bavaria
//     Casino('Spielbank München', const LatLng(48.1405, 11.5806), 'Germany',
//         'https://www.spielbanken-bayern.de/muenchen'),
//     // Berlin
//     Casino('Spielbank Berlin', const LatLng(52.5075, 13.3761), 'Germany',
//         'https://www.spielbank-berlin.de'),
//     // Hamburg
//     Casino('Casino Esplanade', const LatLng(53.5615, 9.9895), 'Germany',
//         'https://www.spielbank-hamburg.de/casino-esplanade'),
//     // Hesse
//     Casino('Spielbank Wiesbaden', const LatLng(50.0826, 8.2416), 'Germany',
//         'https://www.spielbank-wiesbaden.de'),
//     // North Rhine-Westphalia
//     Casino('Casino Duisburg', const LatLng(51.4333, 6.7745), 'Germany',
//         'https://www.westspiel.de/duisburg'),
//     // Lower Saxony
//     Casino('Spielbank Hannover', const LatLng(52.3770, 9.7417), 'Germany',
//         'https://www.spielbank-hannover.de'),
//     // Saxony
//     Casino('Spielbank Leipzig', const LatLng(51.3397, 12.3731), 'Germany',
//         'https://www.spielbanken-sachsen.de/leipzig'),
//   ],
//   'Philippines': [
//     // Metro Manila
//     Casino('Resorts World Manila', const LatLng(14.5176, 121.0198),
//         'Philippines', 'https://www.rwmanila.com'),
//     Casino('City of Dreams Manila', const LatLng(14.5203, 120.9834),
//         'Philippines', 'https://www.cityofdreamsmanila.com'),
//     Casino('Solaire Resort and Casino', const LatLng(14.5285, 120.9832),
//         'Philippines', 'https://www.solaireresort.com'),
//     Casino('Okada Manila', const LatLng(14.5264, 120.9836), 'Philippines',
//         'https://www.okadamanila.com'),
//     // Cebu
//     Casino(
//         'Waterfront Cebu City Hotel and Casino',
//         const LatLng(10.3173, 123.9028),
//         'Philippines',
//         'https://www.waterfronthotels.com.ph'),
//     // Pampanga
//     Casino('Royce Hotel and Casino', const LatLng(15.1861, 120.5604),
//         'Philippines', 'https://www.roycehotelcasino.com'),
//     // Davao
//     Casino('Casino Filipino Davao', const LatLng(7.0669, 125.6095),
//         'Philippines', 'https://www.casinofilipino.ph'),
//     // Tagaytay
//     Casino('Casino Filipino Tagaytay', const LatLng(14.1057, 120.9596),
//         'Philippines', 'https://www.casinofilipino.ph'),
//     // Angeles City
//     Casino('Casino Filipino Angeles', const LatLng(15.1441, 120.5884),
//         'Philippines', 'https://www.casinofilipino.ph'),
//     // Laoag
//     Casino('Casino Filipino Laoag', const LatLng(18.1960, 120.5912),
//         'Philippines', 'https://www.casinofilipino.ph'),
//     // Bacolod
//     Casino('Casino Filipino Bacolod', const LatLng(10.6765, 122.9509),
//         'Philippines', 'https://www.casinofilipino.ph'),
//   ]
// };
